namespace: crudapp

image:
  repository: a54665118b7d.ngrok-free.app/users_service
  tag: "18"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8001

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

readinessProbe:
  httpGet:
    path: /
    port: 8001
  initialDelaySeconds: 10
  periodSeconds: 5